# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-17 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('receive', 'receive'), ('send', 'send')], default='send', max_length=7),
        ),
    ]
